export const BUN_TOP_BOTTOM = 'BUN_TOP_BOTTOM';
export const INGREDIENT_MIDDLE = 'INGREDIENT_MIDDLE';

export const ADD_BURGER_INGREDIENT = 'ADD_BURGER_INGREDIENT';
export const DELETE_BURGER_INGREDIENT = 'DELETE_BURGER_INGREDIENT';

export const ADD_BURGER_CONSTRUCTOR = 'ADD_BURGER_CONSTRUCTOR';
export const DELETE_BURGER_CONSTRUCTOR = 'DELETE_BURGER_CONSTRUCTOR';