export interface IEMAIL_FOTGOT_PASSOWORD {
   type: 'EMAIL_FOTGOT_PASSOWORD';
   payload: string
}

export interface IPOST_FORGOT_PASSWORD {
   type: 'POST_FORGOT_PASSWORD';
}

export interface IPOST_FORGOT_PASSWORD_SUCCESS {
   type: 'POST_FORGOT_PASSWORD_SUCCESS';
   payload: string
}

export interface IPOST_FORGOT_PASSWORD_FAILED {
   type: 'POST_FORGOT_PASSWORD_FAILED';
}

export type TReduxForgot = IEMAIL_FOTGOT_PASSOWORD | IPOST_FORGOT_PASSWORD | IPOST_FORGOT_PASSWORD_SUCCESS | IPOST_FORGOT_PASSWORD_FAILED;
